
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x3e4452"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.cursor]
cursor = "0x5c6370"
text = "0x2c323c"

[colors.normal]
black = "0x2c323c"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x5c6370"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[colors.selection]
background = "0x3e4452"
text = "CellForeground"

[cursor]
style = "Underline"

[font]
size = 11

[font.bold]
family = "FantasqueSansMNerdFont"

[font.bold_italic]
family = "FantasqueSansMNerdFont"

[font.italic]
family = "FantasqueSansMNerdFont"

[font.normal]
family = "FantasqueSansMNerdFont"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

# [terminal.shell]
# program = "/usr/bin/fish"

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.98
title = "Alacritty@Garuda"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[general]
live_config_reload = true

[terminal]
